---
title: "wk6_prac_coding"
author: "chris"
date: "2021/11/17"
output: html_document
---

```{r library}
#first library a few packages that we will use during the practical
#note you may need to install them first...
library(spatstat)
library(here)
library(sp)
library(rgeos)
library(maptools)
library(GISTools)
library(tmap)
library(sf)
library(geojson)
library(geojsonio)
library(tmaptools)
```

#setting up data
```{r read data}
LondonBoroughs <- st_read(here::here('data',
                                     'statistical-gis-boundaries-london',
                                     'ESRI',
                                     'London_Borough_Excluding_MHW.shp'))
qtm(LondonBoroughs)
```
```{r}
library(stringr)
BoroughMap <- LondonBoroughs%>%
  dplyr::filter(str_detect(GSS_CODE,'^E09'))%>%
  st_transform(.,27700)

qtm(BoroughMap)
summary(BoroughMap)
```
```{r}
#now get the location of all blue plaques in the city
BluePlaques <- st_read(here::here('data',
                                  'open-plaques-london-2018-04-08.geojson'))%>%
  st_transform(.,27700)

summary(BluePlaques)
```
```{r}
#plot the blue plaques in the city
tmap_mode('plot')

tm_shape(BoroughMap)+
  tm_polygons(col = 'red',alpha = 0.5)+
tm_shape(BluePlaques)+
  tm_dots(col = 'blue')
  
```
```{r 6.5.1 data cleaning}
#remove duplicates
library(tidyverse)

library(sf)
BluePlaques <- distinct(BluePlaques)
```
```{r 6.5.2 spatial subsetting}
BluePlaquesSub <- BluePlaques[BoroughMap,]#点在map区域中

tmap_mode('plot')
tm_shape(BoroughMap)+
  tm_polygons(col='red',alpha = 0.5)+
tm_shape(BluePlaquesSub)+
  tm_dots(col='blue')
```

```{r 6.5.3 Study area}
#extract the borough
Harrow <- BoroughMap%>%
  filter(.,NAME=='Harrow')

tm_shape(Harrow)+
  tm_polygons(col=NA,alpha=0.5)
```
```{r}
BluePlaquesHarrowSub <- BluePlaquesSub[Harrow,]

tmap_mode('plot')

tm_shape(Harrow)+
  tm_polygons(col = 'red',alpha=0.5)+
tm_shape(BluePlaquesHarrowSub)+
  tm_dots(col='blue',size=0.1)

#now set a window as the borough boundary
window <- as.owin(Harrow)
plot(window)
```
```{r}
#create a point pattern (ppp) object
BluePlaquesHarrowSub <- BluePlaquesHarrowSub%>%
  as(., 'Spatial')

BluePlaquesHarrowSub.ppp <- ppp(x=BluePlaquesHarrowSub@coords[,1],
                                y=BluePlaquesHarrowSub@coords[,2],
                                window=window)

BluePlaquesHarrowSub@coords[,1]

BluePlaquesHarrowSub.ppp%>%
  plot(.,pch=15,cex=0.5,     #pch为填充形状，pch=16实心圆
       main='Blue Plaques Harrow')
```

#6.6 point pattern analysis
```{r 6.6.1 kernel density estimation}
BluePlaquesHarrowSub.ppp%>%
  density(.,sigma=500)%>%
  plot()

BluePlaquesHarrowSub.ppp%>%
  density(.,sigma=1000)%>%
  plot()
```
```{r 6.6.2 quadrat analysis}
#first plot the points
plot(BluePlaquesHarrowSub.ppp,pch=16,cex=0.5,main='Blue Plaques in Harrow')

#count the point in that fall in a 6x6
BluePlaquesHarrowSub.ppp%>%
  quadratcount(.,nx=6,ny=6)%>%
  plot(.,add=T,col='red')
```
```{r}
#run the quadrat count
Qcount <- BluePlaquesHarrowSub.ppp%>%
  quadratcount(.,nx=6,ny=6)%>%
  as.data.frame()%>%
  dplyr::count(Var1=Freq)%>%
  dplyr::rename(Freqquadratcount=n)

Qcount%>%
  summarise_all(class)
```

```{r}
sums <- Qcount%>%
  #calculate the total blue plaques (Var *Freq)
  mutate(total=Var1*Freqquadratcount)%>%
  dplyr::summarise(across(everything(),sum))%>%
  dplyr::select(-Var1)

lambda <- Qcount%>%
  #calculate lambda
  mutate(total=Var1*Freqquadratcount)%>%
  dplyr::summarise(across(everything(),sum))%>%
  mutate(lambda=total/Freqquadratcount)%>%
  dplyr::select(lambda)%>%
  pull(lambda)
```
#Calculate expected using the Poisson formula from above  kis the number of blue plaques counted in a square and is found in the first column of our table
```{r}
QCountTable <- Qcount%>%
  mutate(Pr=((lambda^Var1)*exp(-lambda))/factorial(Var1))%>%
  #now calculate the expected counts based on our total number of plaques
  #and save them to the table
  mutate(Expected=(round(Pr*sums$Freqquadratcount,0)))

#compare the frequency distributions of the observed and expected point patterns
plot(c(1,5),c(0,14),type='n',
     xlab='Number of Blue Plaques(Red=Observed,Blue=Expected)',
     ylab='Frequency of Occurances')
points(QCountTable$Freqquadratcount,
       col='Red',
       type='o',
       lwd=3)
points(QCountTable$Expected,col='Blue',
       type='o',
       lwd=3)
```
```{r}
teststats <- quadrat.test(BluePlaquesHarrowSub.ppp,nx=6,ny=6)

plot(BluePlaquesHarrowSub.ppp,pch=16,cex=0.5,main='Blue Plaques in Harrow')
plot(teststats,add=T,col='red')
```
```{r 6.6.4 Ripley's K}
K <- BluePlaquesHarrowSub.ppp%>%
  Kest(.,correction = 'border')%>%
  plot()
```
```{r 6.7Density-based spatial clustering of applications with noise: DBSCAN}
library(raster)
library(fpc)
```
```{r}
#first check the coordinate reference system of the Harrow spatial polygon:
st_geometry(BoroughMap)

```
```{r}
#first extract the points from the spatial points data frame
BluePlaquesHarrowSubPoints <- BluePlaquesHarrowSub%>%
  coordinates(.)%>%
  as.data.frame()

#now run the dbscan analysis
db <- BluePlaquesHarrowSubPoints%>%
  fpc::dbscan(.,eps=700,MinPts = 4)

#now plot the results
plot(db,BluePlaquesHarrowSubPoints,main='DBSCAN Output',frame=F)
plot(BoroughMap$geometry,add=T)
```

```{r}
#used to find suitable eps value based on the knee in plot
#k is no of nearest neighbours used, use min points
library(dbscan)

BluePlaquesHarrowSubPoints%>%
  dbscan::kNNdistplot(.,k=4)
```
```{r}
library(ggplot2)

db

db$cluster
```

```{r}
BluePlaquesHarrowSubPoints <- BluePlaquesHarrowSubPoints%>%
  mutate(dbcluster=db$cluster)

#Next we are going to create some convex hull polygons to wrap around the points in our clusters.
chulls <- BluePlaquesHarrowSubPoints%>%
  group_by(dbcluster)%>%
  dplyr::mutate(hull = 1:n(),
                hull=factor(hull,chull(coords.x1,coords.x2)))%>%
  arrange(hull)

#As 0 isn’t actually a cluster (it’s all points that aren’t in a cluster) drop it from the dataframe
chulls <- chulls%>%
  filter(dbcluster>=1)
  


```

```{r}
dbplot <- ggplot(data=BluePlaquesHarrowSubPoints,
                 aes(coords.x1,coords.x2,colour=dbcluster,fill=dbcluster))
#add the points in
dbplot <- dbplot+geom_point()
#now the convex hulls
dbplot <- dbplot+geom_polygon(data=chulls,
                              aes(coords.x1,coords.x2,group=dbcluster),
                              alpha=0.5)
#now plot, setting the coordinates to scale correctly and as a black and white plot
dbplot+theme_bw()+coord_equal()
```

```{r}
#add a basemap
#first get the bbox in lat long for Harrow
HarrowWGSbb <- Harrow%>%
  st_transform(.,4326)%>%
  st_bbox()
```

```{r}
library(OpenStreetMap)

basemap <- OpenStreetMap::openmap(c(51.5549876,-0.4040502),c(51.6405356,-0.2671315),
                         zoom=NULL,
                         "stamen-toner")

  # convert the basemap to British National Grid
basemap_bng <- openproj(basemap, projection="+init=epsg:27700")
```

```{r}
autoplot.OpenStreetMap(basemap_bng)+
  geom_point(data=BluePlaquesHarrowSubPoints,
             aes(coords.x1,coords.x2,
                 colour=dbcluster,
                 fill=dbcluster))+
  geom_polygon(data=chulls,
               aex(coords.x1,coords.x2,
                   group=dbcluster,
                   fill=dbcluster),
               alpha=0.5)
```

